<a href="https://colab.research.google.com/github/abuzar01440/abuzar-portfolio/blob/main/data_cleaning_GUCB_scholarship_file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel("/content/planilha_ies.xlsx")
df.head(12)

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:223: UserWarning: Cell O579 is marked as a date but the serial value 6693891.0 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)

,Quadro Geral de Bolsas GCUB-Mob 5ª Edição - Edital 001/2026,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,N°,Região,Estado,Universidade,Sigla,Controle de Bolsas,Nível,O Doutorado requer mestrado como requisito pre...,Nome do Programa - Curso,O Doutorado exige o título de Mestre como pré-...,Website,Cidade,Campus,Website,Inicio,Duração (em meses),Requisito de idioma
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1,Norte,Amazonas,Universidade do Estado do Amazonas ...,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação em Ciências Aplicada...,NaN,https://posgraduacao.uea.edu.br/hematologia/,Manaus,Escola Superior de Ciências da Saúde - \nESA/UEA,NaN,2027-01-03 00:00:00,24,Português e Espanhol.
8,NaN,NaN,NaN,NaN,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação Interdisciplinar em ...,NaN,https://posgraduacao.uea.edu.br/cienciashumanas/,Manaus,Escola Superior de Artes e Turismo - \nESAT/UEA,NaN,2027-01-03 00:00:00,24,Português.
9,NaN,NaN,NaN,NaN,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação em Letras e Artes,NaN,https://ppgla.uea.edu.br,Manaus,Escola Superior de Artes e Turismo - \nESAT/UEA,NaN,2027-02-15 00:00:00,24,Português
10,NaN,NaN,NaN,NaN,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação em Direito Ambiental,NaN,https://pos.uea.edu.br/direitoambiental,Manaus,Escola de Direito -\nED,NaN,2027-03-01 00:00:00,24,"Português, Espanhol."
11,NaN,NaN,NaN,NaN,UEA,NaN,Mestrado,NaN,Gestão e Regulação de Recursos Hídricos /Mestrado,NaN,https://pos.uea.edu.br/profagua/,Manaus,Escola Normal Superior - \nENS,NaN,2027-01-08 00:00:00,24,Português/Espanhol

In [5]:
# remove the first five rows
df = df.iloc[5:]
df.head()

,Quadro Geral de Bolsas GCUB-Mob 5ª Edição - Edital 001/2026,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
5,N°,Região,Estado,Universidade,Sigla,Controle de Bolsas,Nível,O Doutorado requer mestrado como requisito pre...,Nome do Programa - Curso,O Doutorado exige o título de Mestre como pré-...,Website,Cidade,Campus,Website,Inicio,Duração (em meses),Requisito de idioma
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1,Norte,Amazonas,Universidade do Estado do Amazonas ...,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação em Ciências Aplicada...,NaN,https://posgraduacao.uea.edu.br/hematologia/,Manaus,Escola Superior de Ciências da Saúde - \nESA/UEA,NaN,2027-01-03 00:00:00,24,Português e Espanhol.
8,NaN,NaN,NaN,NaN,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação Interdisciplinar em ...,NaN,https://posgraduacao.uea.edu.br/cienciashumanas/,Manaus,Escola Superior de Artes e Turismo - \nESAT/UEA,NaN,2027-01-03 00:00:00,24,Português.
9,NaN,NaN,NaN,NaN,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação em Letras e Artes,NaN,https://ppgla.uea.edu.br,Manaus,Escola Superior de Artes e Turismo - \nESAT/UEA,NaN,2027-02-15 00:00:00,24,Português

In [6]:
#remove the first three columns
df = df.drop(df.columns[:3], axis=1)
df.head()

,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
5,Universidade,Sigla,Controle de Bolsas,Nível,O Doutorado requer mestrado como requisito pre...,Nome do Programa - Curso,O Doutorado exige o título de Mestre como pré-...,Website,Cidade,Campus,Website,Inicio,Duração (em meses),Requisito de idioma
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Universidade do Estado do Amazonas ...,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação em Ciências Aplicada...,NaN,https://posgraduacao.uea.edu.br/hematologia/,Manaus,Escola Superior de Ciências da Saúde - \nESA/UEA,NaN,2027-01-03 00:00:00,24,Português e Espanhol.
8,NaN,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação Interdisciplinar em ...,NaN,https://posgraduacao.uea.edu.br/cienciashumanas/,Manaus,Escola Superior de Artes e Turismo - \nESAT/UEA,NaN,2027-01-03 00:00:00,24,Português.
9,NaN,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação em Letras e Artes,NaN,https://ppgla.uea.edu.br,Manaus,Escola Superior de Artes e Turismo - \nESAT/UEA,NaN,2027-02-15 00:00:00,24,Português

In [7]:
# remove the 2md row
df = df.drop(df.index[1])
df.head()

,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
5,Universidade,Sigla,Controle de Bolsas,Nível,O Doutorado requer mestrado como requisito pre...,Nome do Programa - Curso,O Doutorado exige o título de Mestre como pré-...,Website,Cidade,Campus,Website,Inicio,Duração (em meses),Requisito de idioma
7,Universidade do Estado do Amazonas ...,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação em Ciências Aplicada...,NaN,https://posgraduacao.uea.edu.br/hematologia/,Manaus,Escola Superior de Ciências da Saúde - \nESA/UEA,NaN,2027-01-03 00:00:00,24,Português e Espanhol.
8,NaN,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação Interdisciplinar em ...,NaN,https://posgraduacao.uea.edu.br/cienciashumanas/,Manaus,Escola Superior de Artes e Turismo - \nESAT/UEA,NaN,2027-01-03 00:00:00,24,Português.
9,NaN,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação em Letras e Artes,NaN,https://ppgla.uea.edu.br,Manaus,Escola Superior de Artes e Turismo - \nESAT/UEA,NaN,2027-02-15 00:00:00,24,Português
10,NaN,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação em Direito Ambiental,NaN,https://pos.uea.edu.br/direitoambiental,Manaus,Escola de Direito -\nED,NaN,2027-03-01 00:00:00,24,"Português, Espanhol."

In [8]:
#remove the header and make the row 1 header and reset the index
df = df.iloc[1:]
df.head()

,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
7,Universidade do Estado do Amazonas ...,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação em Ciências Aplicada...,NaN,https://posgraduacao.uea.edu.br/hematologia/,Manaus,Escola Superior de Ciências da Saúde - \nESA/UEA,NaN,2027-01-03 00:00:00,24,Português e Espanhol.
8,NaN,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação Interdisciplinar em ...,NaN,https://posgraduacao.uea.edu.br/cienciashumanas/,Manaus,Escola Superior de Artes e Turismo - \nESAT/UEA,NaN,2027-01-03 00:00:00,24,Português.
9,NaN,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação em Letras e Artes,NaN,https://ppgla.uea.edu.br,Manaus,Escola Superior de Artes e Turismo - \nESAT/UEA,NaN,2027-02-15 00:00:00,24,Português
10,NaN,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação em Direito Ambiental,NaN,https://pos.uea.edu.br/direitoambiental,Manaus,Escola de Direito -\nED,NaN,2027-03-01 00:00:00,24,"Português, Espanhol."
11,NaN,UEA,NaN,Mestrado,NaN,Gestão e Regulação de Recursos Hídricos /Mestrado,NaN,https://pos.uea.edu.br/profagua/,Manaus,Escola Normal Superior - \nENS,NaN,2027-01-08 00:00:00,24,Português/Espanhol

In [9]:
df.columns = df.iloc[0]
df = df[1:].reset_index(drop=True)
display(df.head())

7,Universidade do Estado do Amazonas,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação em Ciências Aplicadas à Hematologia,NaN,https://posgraduacao.uea.edu.br/hematologia/,Manaus,Escola Superior de Ciências da Saúde - \nESA/UEA,NaN,2027-01-03 00:00:00,24,Português e Espanhol.
0,NaN,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação Interdisciplinar em ...,NaN,https://posgraduacao.uea.edu.br/cienciashumanas/,Manaus,Escola Superior de Artes e Turismo - \nESAT/UEA,NaN,2027-01-03 00:00:00,24,Português.
1,NaN,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação em Letras e Artes,NaN,https://ppgla.uea.edu.br,Manaus,Escola Superior de Artes e Turismo - \nESAT/UEA,NaN,2027-02-15 00:00:00,24,Português
2,NaN,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação em Direito Ambiental,NaN,https://pos.uea.edu.br/direitoambiental,Manaus,Escola de Direito -\nED,NaN,2027-03-01 00:00:00,24,"Português, Espanhol."
3,NaN,UEA,NaN,Mestrado,NaN,Gestão e Regulação de Recursos Hídricos /Mestrado,NaN,https://pos.uea.edu.br/profagua/,Manaus,Escola Normal Superior - \nENS,NaN,2027-01-08 00:00:00,24,Português/Espanhol
4,NaN,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação em Educação em Ciênc...,NaN,https://posgraduacao.uea.edu.br/ensinodeciencia/,Manaus,Escola Normal Superior,NaN,2027-01-03 00:00:00,24,Espanhol e Inglês

In [11]:
df.head(2)

7,Universidade do Estado do Amazonas,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação em Ciências Aplicadas à Hematologia,NaN,https://posgraduacao.uea.edu.br/hematologia/,Manaus,Escola Superior de Ciências da Saúde - \nESA/UEA,NaN,2027-01-03 00:00:00,24,Português e Espanhol.
0,NaN,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação Interdisciplinar em ...,NaN,https://posgraduacao.uea.edu.br/cienciashumanas/,Manaus,Escola Superior de Artes e Turismo - \nESAT/UEA,NaN,2027-01-03 00:00:00,24,Português.
1,NaN,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação em Letras e Artes,NaN,https://ppgla.uea.edu.br,Manaus,Escola Superior de Artes e Turismo - \nESAT/UEA,NaN,2027-02-15 00:00:00,24,Português

In [14]:
df.columns

Index(['Universidade do Estado do Amazonas                                                ',
                                                                                      'UEA',
                                                                                        nan,
                                                                                 'Mestrado',
                                                                                        nan,
                            'Programa de Pós-Graduação em Ciências Aplicadas à Hematologia',
                                                                                        nan,
                                             'https://posgraduacao.uea.edu.br/hematologia/',
                                                                                   'Manaus',
                                         'Escola Superior de Ciências da Saúde - \nESA/UEA',
                                                                                        nan,
                                                                        2027-01-03 00:00:00,
                                                                                         24,
                                                                    'Português e Espanhol.'],
      dtype='object', name=7)

In [15]:
df.Mestrado.unique()

array(['Mestrado', 'Doutorado', nan], dtype=object)

In [19]:
df = df[df['Mestrado'] != 'Mestrado'].reset_index(drop=True)
print(f"Unique values in Mestrado column: {df['Mestrado'].unique()}")
display(df.head())

Unique values in Mestrado column: ['Doutorado' nan]

7,Universidade do Estado do Amazonas,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação em Ciências Aplicadas à Hematologia,NaN,https://posgraduacao.uea.edu.br/hematologia/,Manaus,Escola Superior de Ciências da Saúde - \nESA/UEA,NaN,2027-01-03 00:00:00,24,Português e Espanhol.
0,NaN,UEA,NaN,Doutorado,NaN,Programa de Pós-Graduação em Educação em Ciênc...,SIM,https://posgraduacao.uea.edu.br/ensinodeciencia/,Manaus,Escola Normal Superior -\nENS/UEA,NaN,2027-03-01 00:00:00,48,Espanhol cubano e Inglês
1,NaN,UEA,NaN,Doutorado,NaN,Programa de Pós-Graduação em Direito Ambiental,SIM,https://pos.uea.edu.br/direitoambiental,Manaus,Escola de Direito,NaN,2027-03-01 00:00:00,48,Espanhol e Português.
2,NaN,UEA,NaN,Doutorado,NaN,Programa de Pós-Graduação em Medicina Tropical...,SIM,https://ppgmt.uea.edu.br/,Manaus,Escola Superior de Ciências da Saúde - (ESA) /...,NaN,2027-03-01 00:00:00,48,Português e espanhol.
3,NaN,UEA,NaN,Doutorado,NaN,Programa de Pós-graduação em Enfermagem em Saú...,SIM,https://www.proensp.com.br/,Manaus,Escola Superior de Ciências da Saúde - \nESA/UEA,NaN,2027-08-01 00:00:00,48,Português e espanhol.
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
#remove the rows if they nan value in Mestrado column
df = df.dropna(subset=['Mestrado'])
print(f"Unique values in Mestrado column: {df['Mestrado'].unique()}")
display(df.head())

Unique values in Mestrado column: ['Doutorado']

7,Universidade do Estado do Amazonas,UEA,NaN,Mestrado,NaN,Programa de Pós-Graduação em Ciências Aplicadas à Hematologia,NaN,https://posgraduacao.uea.edu.br/hematologia/,Manaus,Escola Superior de Ciências da Saúde - \nESA/UEA,NaN,2027-01-03 00:00:00,24,Português e Espanhol.
0,NaN,UEA,NaN,Doutorado,NaN,Programa de Pós-Graduação em Educação em Ciênc...,SIM,https://posgraduacao.uea.edu.br/ensinodeciencia/,Manaus,Escola Normal Superior -\nENS/UEA,NaN,2027-03-01 00:00:00,48,Espanhol cubano e Inglês
1,NaN,UEA,NaN,Doutorado,NaN,Programa de Pós-Graduação em Direito Ambiental,SIM,https://pos.uea.edu.br/direitoambiental,Manaus,Escola de Direito,NaN,2027-03-01 00:00:00,48,Espanhol e Português.
2,NaN,UEA,NaN,Doutorado,NaN,Programa de Pós-Graduação em Medicina Tropical...,SIM,https://ppgmt.uea.edu.br/,Manaus,Escola Superior de Ciências da Saúde - (ESA) /...,NaN,2027-03-01 00:00:00,48,Português e espanhol.
3,NaN,UEA,NaN,Doutorado,NaN,Programa de Pós-graduação em Enfermagem em Saú...,SIM,https://www.proensp.com.br/,Manaus,Escola Superior de Ciências da Saúde - \nESA/UEA,NaN,2027-08-01 00:00:00,48,Português e espanhol.
5,NaN,UFAM,NaN,Doutorado,NaN,PPGSCA. Programa de Pós-Graduação Sociedade e ...,SIM,ppgsca.ufam.edu.br,Manaus,Manaus,NaN,2027-03-10 00:00:00,48,Mestre em qualquer área do conhecimento

In [23]:
df.Mestrado.value_counts()

Mestrado
Doutorado    318
Name: count, dtype: int64

In [26]:
df.columns

Index(['Universidade do Estado do Amazonas                                                ',
                                                                                      'UEA',
                                                                                        nan,
                                                                                 'Mestrado',
                                                                                        nan,
                            'Programa de Pós-Graduação em Ciências Aplicadas à Hematologia',
                                                                                        nan,
                                             'https://posgraduacao.uea.edu.br/hematologia/',
                                                                                   'Manaus',
                                         'Escola Superior de Ciências da Saúde - \nESA/UEA',
                                                                                        nan,
                                                                        2027-01-03 00:00:00,
                                                                                         24,
                                                                    'Português e Espanhol.'],
      dtype='object', name=7)

In [28]:
df = df.loc[:, df.columns.notna()]
display(df.head())

7,Universidade do Estado do Amazonas,UEA,Mestrado,Programa de Pós-Graduação em Ciências Aplicadas à Hematologia,https://posgraduacao.uea.edu.br/hematologia/,Manaus,Escola Superior de Ciências da Saúde - \nESA/UEA,2027-01-03 00:00:00,24,Português e Espanhol.
0,NaN,UEA,Doutorado,Programa de Pós-Graduação em Educação em Ciênc...,https://posgraduacao.uea.edu.br/ensinodeciencia/,Manaus,Escola Normal Superior -\nENS/UEA,2027-03-01 00:00:00,48,Espanhol cubano e Inglês
1,NaN,UEA,Doutorado,Programa de Pós-Graduação em Direito Ambiental,https://pos.uea.edu.br/direitoambiental,Manaus,Escola de Direito,2027-03-01 00:00:00,48,Espanhol e Português.
2,NaN,UEA,Doutorado,Programa de Pós-Graduação em Medicina Tropical...,https://ppgmt.uea.edu.br/,Manaus,Escola Superior de Ciências da Saúde - (ESA) /...,2027-03-01 00:00:00,48,Português e espanhol.
3,NaN,UEA,Doutorado,Programa de Pós-graduação em Enfermagem em Saú...,https://www.proensp.com.br/,Manaus,Escola Superior de Ciências da Saúde - \nESA/UEA,2027-08-01 00:00:00,48,Português e espanhol.
5,NaN,UFAM,Doutorado,PPGSCA. Programa de Pós-Graduação Sociedade e ...,ppgsca.ufam.edu.br,Manaus,Manaus,2027-03-10 00:00:00,48,Mestre em qualquer área do conhecimento

In [29]:
df.describe()

7,Universidade do Estado do Amazonas,UEA,Mestrado,Programa de Pós-Graduação em Ciências Aplicadas à Hematologia,https://posgraduacao.uea.edu.br/hematologia/,Manaus,Escola Superior de Ciências da Saúde - \nESA/UEA,2027-01-03 00:00:00,24,Português e Espanhol.
count,3,317,318,318,316,318,318,318,318,317
unique,3,55,1,263,313,85,115,35,5,183
top,Universidade Federal de Sergipe ...,UNICAMP,Doutorado,História,https://ufpi.br/,Campinas-SP,Campinas-SP,2027-03-01 00:00:00,48,Português
freq,1,29,318,5,3,28,28,157,295,21

In [30]:
print(f'Total rows: {df.shape[0]}')
print(f'Total columns: {df.shape[1]}')
df.shape

Total rows: 318
Total columns: 10

(318, 10)

In [31]:
df.head()

7,Universidade do Estado do Amazonas,UEA,Mestrado,Programa de Pós-Graduação em Ciências Aplicadas à Hematologia,https://posgraduacao.uea.edu.br/hematologia/,Manaus,Escola Superior de Ciências da Saúde - \nESA/UEA,2027-01-03 00:00:00,24,Português e Espanhol.
0,NaN,UEA,Doutorado,Programa de Pós-Graduação em Educação em Ciênc...,https://posgraduacao.uea.edu.br/ensinodeciencia/,Manaus,Escola Normal Superior -\nENS/UEA,2027-03-01 00:00:00,48,Espanhol cubano e Inglês
1,NaN,UEA,Doutorado,Programa de Pós-Graduação em Direito Ambiental,https://pos.uea.edu.br/direitoambiental,Manaus,Escola de Direito,2027-03-01 00:00:00,48,Espanhol e Português.
2,NaN,UEA,Doutorado,Programa de Pós-Graduação em Medicina Tropical...,https://ppgmt.uea.edu.br/,Manaus,Escola Superior de Ciências da Saúde - (ESA) /...,2027-03-01 00:00:00,48,Português e espanhol.
3,NaN,UEA,Doutorado,Programa de Pós-graduação em Enfermagem em Saú...,https://www.proensp.com.br/,Manaus,Escola Superior de Ciências da Saúde - \nESA/UEA,2027-08-01 00:00:00,48,Português e espanhol.
5,NaN,UFAM,Doutorado,PPGSCA. Programa de Pós-Graduação Sociedade e ...,ppgsca.ufam.edu.br,Manaus,Manaus,2027-03-10 00:00:00,48,Mestre em qualquer área do conhecimento

In [32]:
df.to_excel('cleaned_data.xlsx', index=False)
print('File saved as cleaned_data.xlsx')

File saved as cleaned_data.xlsx